import {
  Archive,
  Building2,
  CalendarDays,
  CalendarClock,
  CalendarOff,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Clock,
  Coins,
  Copy,
  FileText,
  Gift,
  Globe,
  Handshake,
  History,
  House,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LogOut,
  Menu,
  Palette,
  Pause,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Shield,
  Undo2,
  UserPlus,
  UserRound,
  Users,
  UserX,
  Video,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Os ícones do sistema, por nome.
 *
 * Existe um mapa em vez de cada tela importar do `lucide-react` direto por
 * causa da fronteira servidor→cliente: a `Sidebar` é Server Component e
 * entrega a navegação a `NavLinks`, que é cliente — e componente não
 * atravessa essa fronteira como prop, só dado serializável. O nome atravessa;
 * o componente é resolvido do lado de lá.
 *
 * De quebra, o mapa é o catálogo: um ícone que não está aqui não entra na
 * interface, e é isso que mantém "editar" com o mesmo lápis em toda tela.
 */
export const ICONES = {
  archive: Archive,
  building: Building2,
  calendar: CalendarDays,
  "calendar-clock": CalendarClock,
  "calendar-off": CalendarOff,
  check: Check,
  alerta: CircleAlert,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  contract: FileText,
  fuso: Globe,
  handshake: Handshake,
  history: History,
  home: House,
  inbox: Inbox,
  info: Info,
  key: KeyRound,
  dashboard: LayoutDashboard,
  "log-out": LogOut,
  menu: Menu,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  plus: Plus,
  presente: Gift,
  reactivate: RotateCcw,
  refund: Undo2,
  search: Search,
  shield: Shield,
  "user-plus": UserPlus,
  user: UserRound,
  users: Users,
  "user-x": UserX,
  video: Video,
  wallet: Wallet,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type NomeIcone = keyof typeof ICONES;
